### ISSUE TITLE
how do I modify colors

### ISSUE THREAD

**Issue by jasonrberk** [raviriley/agency-jekyll-theme#14]
just getting started with GH pages and Jekyll.  I love the work you've done but I'm confused by all the levels of indirection.  I would like to use a different theme color.  Instead of the brighter yellow, I'm looking to use a more brown / earth tone color scheme.  

I see some commented colors in the _style.yml, but I'm not following what I _could_ put there and how it affects the style.  Does this give me full control of the bootstrap sass variables?

overall, I am just generally confused on what I am allowed to modify within the theme.

**Comment by jasonrberk** [comment]
for example, my "banner" image has a white background, and the header links aren't visible:

![banner](https://user-images.githubusercontent.com/31823413/99189108-94e55080-272d-11eb-8127-d8aac33bf368.PNG)

but when I scroll....the dark background on the header competes with my logo text (can I remove the logo in the floating header?)

![scrolled-banner](https://user-images.githubusercontent.com/31823413/99189196-1f2db480-272e-11eb-8680-a5c329c1fc88.PNG)

**Comment by raviriley** [comment]
Everything in `style.yml` [here](https://github.com/raviriley/agency-jekyll-theme/blob/master/_data/style.yml) is what can be changed using `style.yml`.

If you want to change the highlight color from yellow to brown, you can easily do so by changing `highlight: `.

If you want to change what defaults to white/black to different colors, that is also doable in `style.yml` with `white: ` and `black: `.

These correspond to the Sass variables `$primary`, `$white`, and `$black`, as seen [here(https://github.com/raviriley/agency-jekyll-theme/blob/master/assets/css/agency.scss). 

The only other Sass variables present are the various shades of grey, as seen [here](https://github.com/raviriley/agency-jekyll-theme/blob/master/_sass/base/_variables.scss). I plan on eventually automating the gradient generation so that the greys will update based on user-specified `white` and `black` values.

**Comment by raviriley** [comment]
For the header, I unified the settings for the masthead and navbar / floating header, for ease of use. Do you want to use text instead of the logo in the navbar? But keep the logo for the masthead?

**Comment by raviriley** [comment]
Closing this issue, stale
