### ISSUE TITLE
How to edit the HTML code ?

### ISSUE THREAD

**Issue by santannamv** [raviriley/agency-jekyll-theme#77]
Hi Ravi,
Sorry about my lack of knowledge but I want to edit the icons of the 'Service' section, substitute for a custom image instead the font icon. For doing this I need to edit the 'service.html' file which doesn't exist in my repository, just on yours. I would be very grateful if you give me some tip.

**Comment by raviriley** [comment]
Hi @santannamv, see this line: https://github.com/raviriley/agency-jekyll-theme/blob/1656eafb03c2ae026ba7ed88871984b62377fabc/_data/sitetext.yml#L26

You can change the icon in the [`sitetext` file](https://github.com/raviriley/agency-jekyll-theme/blob/master/_data/sitetext.yml). If a font awesome icon does not suit your needs and you want to use your own image, you can modify the services file to use an `img` tag instead of an icon `i` tag. 

Click [here](https://github.com/raviriley/agency-jekyll-theme/blob/master/_includes/services.html)  to see the services file. You can copy the linked file to `_includes/services.html` and modify as needed in your repo.

**Comment by raviriley** [comment]
For any other files you want to override, simply add them with the same path as my repo and then modify to your needs.
